# Generated by Django 3.0.5 on 2020-04-30 11:54

from django.db import migrations, models
import short_urls.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250, validators=[short_urls.utils.validate_url])),
                ('short', models.CharField(blank=True, max_length=7, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cnt', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
